storage:
  sqlite:
    file: core.db

features:
  wither-sound:
    enabled: true
  tokens:
    enabled: true
  creativeitemcontrol:
    enabled: true
  command-maker:
    enabled: true
  player-broadcast:
    enabled: true
  chat-patrol:
    enabled: true
  zel-addon:
    enabled: true
  bottle-xp:
    enabled: true
  sleep-cap:
    enabled: true
  void-guard:
    enabled: true
  geyser-combat-log:
    enabled: true
  chatgames:
    enabled: true
  beacon-hider:
    enabled: true
  zelduels:
    enabled: true
