name: FriendlyCore
main: com.friendlysmp.core.FriendlyCorePlugin
version: 1.0.0
api-version: "1.20"
folia-supported: true
softdepend: [PlaceholderAPI, Vault]
depend: [packetevents]

commands:
  friendlycore:
    description: FriendlyCore admin command
    usage: /friendlycore reload
  withersound:
    description: Toggle the Wither death sound for yourself.
    usage: /withersound [toggle|on|off|status]
  token:
    description: Token command
    usage: /token
  cic:
    description: CreativeItemCommand Admin command
    usage: /cic <reload|list|store>
  commandmaker:
    description: CommandMaker admin command
    usage: /commandmaker reload
  pbroadcast:
    description: Send a paid broadcast message
    usage: "/pbroadcast <message>"
    permission: friendlycore.pbc.use
    aliases: [pbc]
  pbreload:
    description: Reload PlayerBroadcast config
    usage: "/pbreload"
    permission: friendlycore.pbc.admin


permissions:
  friendlycore.admin:
    default: op
  # Tokens
  friendlycore.tokens.admin:
    default: op
  # CIC
  friendlycore.cic.bypass.enchantments:
    description: Bypass enchantment checks
    default: op
  friendlycore.cic.bypass.attributes:
    description: Bypass attribute checks
    default: op
  friendlycore.cic.bypass.potions:
    description: Bypass custom potion checks
    default: op
  friendlycore.cic.admin:
    default: op
  friendlycore.cic.give:
    default: op
  # PBC
  friendlycore.pbc.use:
    description: Allows using the broadcast command
    default: op
  friendlycore.pbc.admin:
    description: Allows reloading the plugin
    default: op