storage:
  sqlite:
    file: core.db

features:
  wither-sound:
    enabled: true
    debug: false
  tokens:
    enabled: true
  creative-item-control:
    enabled: true
  command-maker:
    enabled: true


tokens:
  claim-until-day: 7
  excluded-worlds:
    - builds
    - vip
    - flat
  ranks:
    vip:
      permission: tokens.vip
      amount: 3
    legend:
      permission: tokens.legend
      amount: 5



creativeitemcontrol:
  config:
    playeralerts: true # Send a message to the player attempting to get the item

    worlds: # Worlds in which the plugin is active
      - builds
      - vip
      - flat
    blacklist: false # If true, above worlds config will act as a blacklist
    give-cooldown: 5 # Seconds before being able to use /cic give again. 0 = no cooldown



  enchantments:
   # By default, only regular enchantments and levels will be allowed.
   # Action to take when impossible enchants are found. Options:
   # LOWER - Set enchants to the highest possible value for that item
   # REMOVE - Remove enchantments from the item all-together
   # DELETE - Delete the item
    enabled: true # Enable enchantment checks?
    action: LOWER
    allow-incompatible: false # Whether or not to allow incompatible enchantments (Sharpness with Smite, Infinity with Mending, etc)

  attributes:
  # By default, no attribute modifying items will be allowed
  # Action to take when attribute modifiers are found. Options:
  # REMOVE - Remove the attribute modifiers from the item
  # DELETE - Delete the item
    enabled: true
    action: DELETE

  potions:
    enabled: true


commandmaker:
  enabled-commands:
    - website
    - limits
    - store
    - map
    - ticket
    - support

  commands:
    website:
      aliases: []
      message:
        - "&bVisit our website at&f: <click:open_url:'friendlysmp.com'>friendlysmp.com</click>"
    limits:
      message:
        - "&bFor a full list of limits visit <click:open_url:'http://friendlysmp.com/limits'>http://friendlysmp.com/limits</click>"
    store:
      message:
        - "&bVisit our webstore at&f <click:open_url:'https://friendlysmp.com/shop'>friendlysmp.com/shop</click>"
    map:
      message:
        - "&bView our World Map at&f: <click:open_url:'friendlysmp.com/map'>friendlysmp.com/map</click>"
    ticket:
      message:
        - "&aReceive support from a staff member at&f <click:open_url:'friendlysmp.com/tickets'>friendlysmp.com/tickets</click>"
    support:
      message:
        - "&bReceive support from a staff member at&f: <click:open_url:'friendlysmp.com/tickets'>friendlysmp.com/tickets</click>"
