name: FriendlyCore
main: com.friendlysmp.core.FriendlyCorePlugin
version: 1.0.0
api-version: "1.20"
folia-supported: true
softdepend: [PlaceholderAPI]
depend: [packetevents]

commands:
  friendlycore:
    description: FriendlyCore admin command
    usage: /friendlycore reload
  withersound:
    description: Toggle the Wither death sound for yourself.
    usage: /withersound [toggle|on|off|status]
  token:
    description: Token command
    usage: /token
  cic:
    description: CreativeItemCommand Admin command
    usage: /cic <reload|list|store>
  commandmaker:
    description: CommandMaker admin command
    usage: /commandmaker reload


permissions:
  friendlycore.admin:
    default: op
  # Tokens
  friendlycore.tokens.admin:
    default: op
  # CIC
  friendlycore.cic.bypass.enchantments:
    description: Bypass enchantment checks
    default: op
  friendlycore.cic.bypass.attributes:
    description: Bypass attribute checks
    default: op
  friendlycore.cic.bypass.potions:
    description: Bypass custom potion checks
    default: op
  friendlycore.cic.admin:
    default: op
  friendlycore.cic.give:
    default: op