config:
  enabled: true
  player-alerts: true 
  alert-cooldown: 1000

  worlds:
    - builds
    - vip
    - flat
  blacklist: false
  give-cooldown: 5
  check-dispensers: true

enchantments:
  enabled: true
  action: LOWER
  allow-incompatible: false

attributes:
  enabled: true
  action: DELETE

potions:
  enabled: true

components:
  enabled: true
  blocked:
    - minecraft:glider
    - minecraft:consumable
    - minecraft:equippable

messages:
  alerts:
    components: "<b><red>Items with custom components are not allowed here!"
    attributes: "<b><red>Items with attribute modifiers are not allowed here!"
    enchantments: "<b><red>Items with impossible enchantments are not allowed here!"
    potions: "<b><red>Custom potions are not allowed here!"
  commands:
    exclude: "&aStored {type} as \"{id}\"."
    remove: "&aRemoved excluded item \"{id}\"."
    listempty: "&eNo excluded items stored."
    give: "&aGave \"{id}\" to &f&a{player}."
    giveinvalid: "&cNo excluded item found with id \"{id}\"."
    giveothersfail: "&cYou do not have permission to give to other players!"
    playernotfound: "&cPlayer \"{player}\" not found."
    specifyplayer: "&cSpecify a player: /cic give <id> <player>"
    invalidworld: "&cYou cannot use this in this world!"
    oncooldown: "&cYou must wait {time}s before receiving this item again."
    noperm: "&cYou do not have permission!"
